DROP TABLE IF EXISTS restaurantes;

CREATE TABLE restaurantes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome_fantasia VARCHAR(50) NOT NULL,
  cnpj VARCHAR(50) NOT NULL,
  email VARCHAR(50),
  ativo BOOLEAN NOT NULL,
  endereco_id INTERGER,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(endereco_id) REFERENCES addresses(id)
);

DROP TABLE IF EXISTS pedidos;

CREATE TABLE pedidos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  descr VARCHAR(50) UNIQUE NOT NULL,
  valor DECIMAL(17,2) NULL DEFAULT NULL,
  restaurant_id INTEGER,
  endereco_id INTERGER,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(restaurant_id) REFERENCES restaurantes(id)
);

DROP TABLE IF EXISTS delivery;

CREATE TABLE delivery (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pedido_id INTEGER NOT NULL,
  status VARCHAR(30),
  couriers_id INTEGER NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(pedido_id) REFERENCES pedidos(id),
  FOREIGN KEY(couriers_id) REFERENCES couriers(id)
);

DROP TABLE IF EXISTS addresses;

CREATE TABLE addresses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  city VARCHAR(50) NOT NULL,
  state_a VARCHAR(30) NOT NULL,
  street VARCHAR(50),
  number INTEGER,
  neighborhood VARCHAR(50),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS couriers;

CREATE TABLE couriers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(30) NOT NULL,
  email VARCHAR(30) UNIQUE NOT NULL,
  password VARCHAR(30) NOT NULL,
  cpf VARCHAR(30) UNIQUE NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(30) NOT NULL,
  email VARCHAR(30) UNIQUE NOT NULL,
  password VARCHAR(30) NOT NULL,
  endereco_id INTEGER,
  cpf VARCHAR(30) UNIQUE NOT NULL,
  FOREIGN KEY(endereco_id) REFERENCES addresses(id)
);
